### ISSUE TITLE
Adding of author tag to blog posts

### ISSUE THREAD

**Issue by vipulgupta2048** [pythonindia/inpycon-blog#263]
* **Do you want to request a *feature* or report a *bug*?**
I feel like this is something we have been missing in PyCon India blogs for some time now. Having author tags is a great way to credit the writers for the blogs and can be done pretty easily by adding it to our template. 

**Roadlocks**
- All the posts from this point before won't have any author tags and will possibly lead to errors (I have to test this)
- If there are no errors, we have to leave them empty or give them a default value. Which is okay. 
What do you all think?

**Comment by ananyo2012** [comment]
+1 for the feature. Yes using a default value like `anonymous` should be fine for the older posts.

**Comment by ananyo2012** [comment]
On second thought just keep it blank. This is a static blog so we can just add the Author if it exists.

**Comment by ananyo2012** [comment]
@vipulgupta2048 With reference to your [comment](https://github.com/pythonindia/inpycon-blog/pull/265#discussion_r426842620) in #265

I think instead of separate author pages we can let the author add the link to his/her bio. We just need to come up with a proper structure how they should mention in the blog markup.

**Comment by vipulgupta2048** [comment]
Roger that, @ananyo2012 Do add the structure to the README when you can. 
Closing #263 via #266
